#!/bin/bash

# Bash script to create the initial directory structure for the 
# generated application and artifacts.
# Chris Joakim, Microsoft, October 2021

echo '---------------------------------'
echo 'start create_directories.sh'

source env.sh

echo 'M2C_APP_DIR is '$M2C_APP_DIR

mkdir -p $M2C_APP_DIR
mkdir -p $M2C_APP_DIR/artifacts
mkdir -p $M2C_APP_DIR/artifacts/adf/dataset
mkdir -p $M2C_APP_DIR/artifacts/adf/linkedService
mkdir -p $M2C_APP_DIR/artifacts/adf/pipeline
mkdir -p $M2C_APP_DIR/artifacts/shell
mkdir -p $M2C_APP_DIR/artifacts/shell/data
mkdir -p $M2C_APP_DIR/artifacts/shell/mongo
mkdir -p $M2C_APP_DIR/artifacts/shell/out
mkdir -p $M2C_APP_DIR/artifacts/shell/pysrc
mkdir -p $M2C_APP_DIR/artifacts/shell/tmp

mkdir -p $M2C_APP_DIR/data
mkdir -p $M2C_APP_DIR/data/metadata

mkdir -p $M2C_APP_DIR/databases

if test -f $M2C_APP_DIR/data/metadata/migrated_databases_list.txt; then
    echo 'removing existing migrated_databases_list.txt (will be regenerated by this script)'
    rm $M2C_APP_DIR/data/metadata/migrated_databases_list.txt
fi

if test -f $M2C_APP_DIR/data/metadata/manifest.json; then
    echo 'removing existing manifest.json (will be regenerated by this script)'
    rm $M2C_APP_DIR/data/metadata/manifest.json
fi

databases=$M2C_MONGODB_DATABASE_NAMES
for i in $(echo $databases | sed "s/,/ /g")
do
    # call your procedure/other scripts here below
    echo "$i" >> $M2C_APP_DIR/data/metadata/migrated_databases_list.txt
    echo '$i added to migrated_databases_list.txt'
done
echo 'migrated_databases_list.txt created'

echo "{}" > $M2C_APP_DIR/data/metadata/manifest.json
echo 'manifest.json created'

echo 'finish create_directories.sh'
echo '---------------------------------'
